#!/bin/sh

# Convenience script for running SWIG before it is installed.
# Intended for ad-hoc usage and not by the test-suite or examples.

builddir=`dirname "$0"`
SWIG_LIB='/home/pclee/Desktop/workarea/py4-install/swig-3.0.12/Lib'
export SWIG_LIB
exec "$builddir/swig" "$@"
